name: daprexample
extensions:
- name: dapr
  components-path: "./dapr/components/"
  services:
    daprexample-web:
      http-port: 7002
      grpc-port: 7003
    publisher:
      http-port: 8002
      grpc-port: 8003
      enabled: true
      
services:
- name: daprexample-web
  project: src\DaprExample.Web\DaprExample.Web.csproj
  bindings:
  - port: 44352
- name: publisher
  project: test\DaprExample.HttpApi.Client.ConsoleTestApp\DaprExample.HttpApi.Client.ConsoleTestApp.csproj
- name: redis
  image: redis
  bindings:
    - port: 6973
      containerPort: 6379
